[package]
name = "gnulightning-sys"
version = "2.3.0"
links = "foo"
build = "build.rs"
edition = "2018"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
pkg-config = "0.3"